### ISSUE TITLE
Service structure hedley example

### ISSUE THREAD

**Issue by amitaibu** [YaronMiro/AngularJs-UI-Router---Example#4]
You shouldn't be injecting the Service to the controller, for that you can use `resolve`. Also the service could be copied from hedley, as it provides a better structure + caching.

`+` very nice work so far :)

**Comment by YaronMiro** [comment]
@amitaibu 
OK, thank's for the feedback I will check `hedley` and update the code accordingly.

**Comment by YaronMiro** [comment]
- [ ] Use cache service example.

// cebter div on responsive image
http://jsfiddle.net/pux7q/2/
http://stackoverflow.com/questions/20593766/css-vertical-center-responsive-image-within-100-height-absolute-div

http://www.robshouse.net/content/youtube-data-api-v3-how-get-developerkey

http://stackoverflow.com/questions/24634930/unable-to-load-url-into-iframe-via-angularjs-controller

https://gist.github.com/guyjz/5542011

http://stackoverflow.com/questions/24634930/unable-to-load-url-into-iframe-via-angularjs-controller

http://gdata.youtube.com/feeds/api/videos?orderby=relevance&max-results=1&alt=json&format=5&vq=trailer "
